# Generated by Django 4.2.1 on 2023-05-07 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import post_order.models.client


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[post_order.models.client.validate_phone], verbose_name='Номер телефона клиента')),
                ('mobile_code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(900), django.core.validators.MaxValueValidator(999)], verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(max_length=50, verbose_name='Тэг (произвольная метка)')),
                ('timezone', models.CharField(max_length=255, validators=[post_order.models.client.validate_timezone])),
            ],
        ),
        migrations.CreateModel(
            name='PostOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата и вермя запуска расыылки')),
                ('message_text', models.CharField(max_length=300, verbose_name='Текст сообщения для доставки клиенту')),
                ('filter_property', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фильтр свойств клиентов для доставки (тег или код мобильного оператора)')),
                ('end_time', models.DateTimeField(verbose_name='Дата времени окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания (отправки)')),
                ('status', models.CharField(choices=[('processing', 'Отправка сообщения'), ('sent', 'Отправлено'), ('error', 'Ошибка'), ('expired', 'Доставка просрочена')], max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MESSAGE_CLIENT', to='post_order.client')),
                ('post_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MESSAGE_POSTORDER', to='post_order.postorder')),
            ],
        ),
    ]
